name: flutter_apps
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4
  lottie: ^3.3.1
  shared_preferences: ^2.0.15
  flutter_svg: ^2.0.5
  flutter_localization: ^0.3.1
  flutter_skeleton_ui: ^0.0.6
  intl: ^0.19.0
  dio: ^5.7.0
  dio_smart_retry: ^7.0.1
  flutter_riverpod: ^2.6.1
  toastification: ^2.3.0
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.4
  material_segmented_control: ^5.0.1
  firebase_core: ^3.10.1
  saver_gallery: ^4.0.1
  screenshot: ^3.0.0
  carousel_slider_plus: ^7.1.0
  flutter_otp_text_field: ^1.4.0+2
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  # Or use mocktail
  mocktail: ^1.0.4
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/icons/
      - assets/images/
      - assets/animations/

  fonts:
    - family: IBM Plex Sans Arabic
      fonts:
        - asset: assets/fonts/ibm_plex_sans_arabic_regular.ttf
        - asset: assets/fonts/ibm_plex_sans_arabic_bold.ttf
          weight: 700
        - asset: assets/fonts/ibm_plex_sans_arabic_semibold.ttf
          weight: 600
        - asset: assets/fonts/ibm_plex_sans_arabic_medium.ttf
          weight: 500
